CREATE TABLE DATA.REGION (ID integer, DECRIPTION VARCHAR(50));


ALTER TABLE DATA.REGION ADD CONSTRAINT PK_REGION_ID PRIMARY KEY (ID);


CREATE TABLE DATA.COUNTRY (ID integer, REGION integer, DESCRIPTION VARCHAR(50));


ALTER TABLE DATA.COUNTRY ADD CONSTRAINT PK_COUTRY_ID PRIMARY KEY (ID);


ALTER TABLE DATA.COUNTRY ADD CONSTRAINT FK_CONTRY_REGION
FOREIGN KEY (REGION) REFERENCES DATA.REGION(ID);


CREATE TABLE DATA.CITY(ID integer, COUNTRY integer, DESCRIPTION VARCHAR(50),
																								LATITUDE double precision, LOGTITUDE double precision, DATASET VARCHAR(10));


ALTER TABLE DATA.CITY ADD CONSTRAINT PK_CITY_ID PRIMARY KEY (ID);


ALTER TABLE DATA.CITY ADD CONSTRAINT FK_CITY_COUNTRY
FOREIGN KEY (COUNTRY) REFERENCES DATA.COUNTRY(ID);


CREATE TABLE DATA.MEASUREMENT(CITY integer, MARK timestamp WITHOUT TIME ZONE,
																															TEPARATURE double precision);


ALTER TABLE DATA.MEASUREMENT ADD CONSTRAINT FK_MEASURMENT_CITY
FOREIGN KEY (CITY) REFERENCES DATA.CITY(ID);


CREATE TABLE DATA.COASTILNE(SHAPE integer, SETGMET integer, LATITUDE double precision, LONGITUDE double precision);
